package M2;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DATE = 8;
  public static final int PACKAGE = 3;
  public static final int BODY = 13;
  public static final int SECTION = 9;
  public static final int EOF = 0;
  public static final int TITLE = 6;
  public static final int DOC_CLASS = 2;
  public static final int error = 1;
  public static final int BEGIN_DOC = 4;
  public static final int TEXT = 12;
  public static final int NEWLINE = 7;
  public static final int MAKE = 11;
  public static final int BF = 10;
  public static final int END_DOC = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOC_CLASS",
  "PACKAGE",
  "BEGIN_DOC",
  "END_DOC",
  "TITLE",
  "NEWLINE",
  "DATE",
  "SECTION",
  "BF",
  "MAKE",
  "TEXT",
  "BODY"
  };
}

